name: You’re gonna be the death of me
permalink: /blog/:slug
collections:
    gallery:
        output: true
    roundups:
        output: true
    story:
        output: true
defaults:
  - scope:
      path: "_roundups"
    values:
      layout: 1.1-gallery
      permalink: /gallery/roundups/:path
      subpage: gallery/roundups