name: You’re gonna be the death of me
permalink: /blog/:slug
collections:
    gallery:
        output: true
    roundups:
        output: true
    story-v1:
        output: true
defaults:
  - scope:
      path: "_roundups"
    values:
      layout: 1.1-gallery
      permalink: /gallery/roundups/:path
      subpage: gallery/roundups
  - scope:
      path: "_story-v1"
    values:
      layout: 1.1-story-v1
      permalink: /story/v1/:path
      subpage: story/v1